site_name: Aircraft classifiers for TAK
site_url: https://aircot.rtfd.io/
repo_url: https://github.com/snstac/aircot/
site_description: Software for classifying aircraft within the Team Awareness Kit (TAK) ecosystem of products.
site_author: Greg Albrecht <gba@snstac.com>
copyright: Copyright Sensors & Signals LLC https://www.snstac.com

theme:
  name: material
  highlightjs: true
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate 
    
plugins:
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences